### ISSUE TITLE
Add date/year to footer

### ISSUE THREAD

**Issue by ANIALLATOR114** [ANIALLATOR114/SimplyTransport#33]
Its already set up with flexbox, just needs a consistent `2023` there.
This should be generated using code and **not** hardcoded

**Comment by jepoy92** [comment]
Hello, I'd like to work on this issue!

**Comment by ANIALLATOR114** [comment]
Heya @jepoy92  
You're more than welcome 🍰 

The ideal outcome is an additional `footer-item` in `footer.html` which will then be used on every page.
![image](https://github.com/ANIALLATOR114/SimplyTransport/assets/116189545/759053fb-fb87-4672-b874-740a2602e359)

The text display should be  `© 2023 SimplyTransport`

Any troubles or question let me know 👍

**Comment by jepoy92** [comment]
Hi, I'm having some issues launching the app to see my changes happen live. Is there a way I can do this?

**Comment by ANIALLATOR114** [comment]
Have you followed the steps in the README?

There are steps there outlining what you need to do for a local development setup.

What command are you trying to run?
What errors are you seeing?

**Comment by jepoy92** [comment]
I'm having issues running litestar, when running the litestar run command i get the "Could not find a Litestar app or factory" error. Also, I'm not sure where to grab my own .env variables either.

**Comment by ANIALLATOR114** [comment]
Ah I see 👍 

When you run` litestar <command>` it will try and find the Litestar app to launch. I have it set so it looks for a `.env` file with a `LITESTAR_APP` variable set inside it.

In the .env.example file you can see what this is supposed to look like
`LITESTAR_APP=SimplyTransport.app:create_app` <- you shouldnt need to alter this 👍 

So what's needed is:
1. Have a .env file in the root directory
2. Have the file contain the same variables as the example
3. Set the variables 

As for the values to set the variables too, the only ones I think you need to change are the database ones.
```
# Database
DB_URL=postgresql+asyncpg://example:example@localhost:5432/example
DB_URL_SYNC=postgresql+psycopg2://example:example@localhost:5432/example
DB_ECHO=false

# Postgres Docker
POSTGRES_DB=example
POSTGRES_USER=example
POSTGRES_PASSWORD=example
```

Here is how they map together. (put whatever you set in the `POSTGRES_VARIABLE` into its relevant place in the URL)
![image](https://github.com/ANIALLATOR114/SimplyTransport/assets/116189545/8c1b1013-cca1-4d6a-9525-ab540f527380)

If you already created the docker container with the database I think you might need to delete it and create it again after you've filled in these values. You may use any strings for these values as the database will only be on your local machine.

I'll update the docs this evening to be more explicit about how to do this 🦖

**Comment by ANIALLATOR114** [comment]
https://github.com/ANIALLATOR114/SimplyTransport/commit/3dc956b87acb501fcb51b6b734ed6a4c172b1608
README updated with steps above for future reference.

**Comment by jepoy92** [comment]
Hi, I've made some progress trying to get the project to run locally but, I'm still running into the same issue. 

My .env has been updated so that the strings listed in your example were edited, I am now able to launch a docker container, but for some reason I'm unable to get litestar to work. Do i also update the DB_URL_POSTGRES as well? Not sure what's causing the issue.

**Comment by ANIALLATOR114** [comment]
@jepoy92 
I just tested the process fresh from the beginning to try and reproduce.
I followed the steps as I outlined in the docs and it worked correctly for me.
Here are briefly the steps I followed.

1. I created a new folder
2. I cloned the repo into that folder
3. I entered the folder and created a new virtual environment
4. I installed the dependencies
5. I copied the .env-example file and created a new .env file
6. I set the ENV variables I outlined before
7. I ran the command litestar -run
8. The application started up correctly

The error you're getting would indicate that a .env file is not present in the location you're running `litestar -run` from, or the .env file doesnt have `LITESTAR_APP` defined inside it.
Can you please double check you're in the root of the project when running the command `litestar -run` 
Can you also double check you have a `.env` file present in the root directory?
Inside the `.env` file the very first line should be exactly `LITESTAR_APP=SimplyTransport.app:create_app`

When you run that command it will start looking for a Litestar application in a few different places. It will find it in the `.env` file if one is present under the name `LITESTAR_APP`

If still not working could you please provide a screenshot of your terminal with the current working directory visible and the error produced when you run the command.

**Comment by jepoy92** [comment]
Hello, here's what I currently have:
![image](https://github.com/ANIALLATOR114/SimplyTransport/assets/65995065/e477c8c3-4526-41c7-b017-bf3c25330d4e)

**Comment by ANIALLATOR114** [comment]
@jepoy92 
Do you have your virtual environment activated? `python-dotenv` is one of the dependencies in this project that automatically pick up the `.env `file config for you. I don't use powershell but I would expected to see (venv) at the beginning of your command line indicating the environment is active.
If you dont have it activated then you wont have any of the dependencies installed (unless you installed them globally - please don't do this!)
Here is some more detailed explanation about this [**stackoverflow**](https://stackoverflow.com/questions/41972261/what-is-a-virtualenv-and-why-should-i-use-one)
Please ensure you are inside your venv first, then install the dependencies, then try running the commands. 

You can override this behaviour another way by specifying the app location directly.
`litestar --app SimplyTransport.app:create_app run`

This is doing the exact same thing but passing in a specific app location to use instead of automatically.

**Comment by jepoy92** [comment]
I have the virtual environment active, and attempted to use both the litestar run and litestar --app SimplyTransport.app:create_app run command but received this in my terminal:

$ litestar --app SimplyTransport.app:create_app run
Using Litestar app from env: 'SimplyTransport.app:create_app'
Traceback (most recent call last):
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\logging\config.py", line 581, in configure        
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\logging\config.py", line 786, in configure_handler
    raise ValueError('No handlers specified for a QueueHandler')
ValueError: No handlers specified for a QueueHandler

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Scripts\litestar.exe\__main__.py", line 7, in <module>
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\litestar\__main__.py", line 6, in run_cli
    litestar_group()
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich_click\rich_command.py", line 125, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\litestar\cli\_utils.py", line 242, in make_context
    self._prepare(ctx)
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\litestar\cli\_utils.py", line 224, in _prepare
    env = ctx.obj = LitestarEnv.from_env(ctx.params.get("app_path"), ctx.params.get("app_dir"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\litestar\cli\_utils.py", line 120, in from_env
    loaded_app = _load_app_from_path(app_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\litestar\cli\_utils.py", line 295, in _load_app_from_path
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module 
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\jeffr\Desktop\Coding Projects\SimplyTransport\SimplyTransport\app.py", line 33, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "C:\Users\jeffr\Desktop\Coding Projects\SimplyTransport\SimplyTransport\app.py", line 18, in create_app       
    return Litestar(
           ^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\litestar\app.py", line 445, in __init__
    self.get_logger = self.logging_config.configure()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\site-packages\litestar\logging\config.py", line 229, in configure
    config.dictConfig(values)
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\logging\config.py", line 912, in dictConfig       
    dictConfigClass(config).configure()
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Lib\logging\config.py", line 588, in configure        
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'queue_listener'
(venv)

here's how I've set up my .env file:

# Database
DB_URL=postgresql+asyncpg://jeffc:1234@localhost:5432/simplytransport
DB_URL_SYNC=postgresql+psycopg2://example:example@localhost:5432/example
DB_ECHO=false

# Postgres Docker
POSTGRES_DB=simplytransport
POSTGRES_USER=jeffc
POSTGRES_PASSWORD=1234

I'm not sure why i'm having such a hard time getting my litestar app running. i hope that helps.

**Comment by ANIALLATOR114** [comment]
@jepoy92 
The virtual environment must not be just created it must also be activated (your command line must be inside it)
You said its active but I can see from the call stack that you are outside of the virtual environment.

`File "C:\Users\jeffr\AppData\Local\Programs\Python\Python312\Scripts\litestar.exe_main.py"`
This is using a globally scoped Python interpreter. 

When you're in the root directory you need to run the powershell command that points at the activation of your venv.
https://stackoverflow.com/questions/1365081/virtualenv-in-powershell

_"I'm not sure why i'm having such a hard time getting my litestar app running"_
You just havn't worked with virtual environments yet I imagine, anything done in python uses these and they're very straightforward. https://www.youtube.com/watch?v=APOPm01BVrk&t=47s
This is a great tutorial about them ^ and highly recommended.

So once its active, you need to run the `pip install -r requirements.txt` again to make sure you have all the dependencies and everything will work then 👍

**Comment by jepoy92** [comment]
Success, I will get started on working on this ticket. Thank you for your patience.
